### ISSUE TITLE
withPrefix prints no space between currency and value

### ISSUE THREAD

**Issue by eleftrik** [sebastiansulinski/laravel-currency#2]
Just installed this package. 

```
Currency::withPostfix($value)
```

shouldn't print a space between the currency and the value?
Actually it returns e. g. "€38.00"

Is there any configuration to modify?

Thank you

**Comment by sebastiansulinski** [comment]
You don't usually put space between the currency symbol and the value, but if you'd like one then you can simply create a new currency class for eur - like this one [https://github.com/sebastiansulinski/laravel-currency/blob/master/src/Currencies/EUR.php](https://github.com/sebastiansulinski/laravel-currency/blob/master/src/Currencies/EUR.php)
and replace it in your `config/currency.php` file. 
You could then add space after the currency symbol as a value for the `$prefix` property.

**Comment by eleftrik** [comment]
Thank you @sebastiansulinski. You're absolutely right: http://publications.europa.eu/code/en/en-370303.htm

> However, the euro sign (when permitted) is followed by the amount without the intervening hard space
