### ISSUE TITLE
withPrefix $decimal_points default value

### ISSUE THREAD

**Issue by eleftrik** [sebastiansulinski/laravel-currency#3]
In the examples I see

```
withPrefix($values, $currency = null, $decimal_points = 2)
```

but if I run

```
Currency::withPrefix($item->price)
```

or

```
Currency::withPrefix($item->price, 'eur')
```

there are no decimals in the price returned.

Thank you

**Comment by sebastiansulinski** [comment]
You're right - the documentation has it incorrect - it's only `decimal()` method that has default `$decimal_points = 2` - other methods have `null` by default.
I've now updated the docs - please use it as `Currency::withPrefix($item->price, 'eur', 2)` to get 2 decimal places.
