### ISSUE TITLE
Return error

### ISSUE THREAD

**Issue by daniberv** [sebastiansulinski/laravel-currency#6]
Works beautifully on the local machine.
But it cause the error on the host.
`Type error: Return value of SSD\Currency\Providers\CookieProvider::set() must be an instance of SSD\Currency\Providers\void, none returned`

**Comment by sebastiansulinski** [comment]
Please check version of php on your server -void returned statement has been introduced in php 7.1

**Comment by daniberv** [comment]
Sorry. That's right. Solved
