### ISSUE TITLE
How to avoid prefix

### ISSUE THREAD

**Issue by robertnicjoo** [sebastiansulinski/laravel-currency#8]
Hi,

I am getting my prices in javascript and calculate them, for that matter i need to avoid prefixes and just get price it selves, how do i do that?

basic
```
$10
```

what i want

```
10
```

**Comment by robertnicjoo** [comment]
anyone?

**Comment by sebastiansulinski** [comment]
You can use `decimal()` method to get just a decimal value.

**Comment by robertnicjoo** [comment]
@sebastiansulinski  hi, and if i don't want to have decimals?

with decimals my price become like `10.000.000` i need clean price like `10000000`

**Comment by sebastiansulinski** [comment]
Ok - I'll look into it.

**Comment by sebastiansulinski** [comment]
Check new release - in particular new index added to the config `value_as_integer` and new method `integer()`
